name: Update Repo Views

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get repo traffic
        id: traffic
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/traffic/views)

          echo $response

          views=$(echo $response | jq '.count')
          uniques=$(echo $response | jq '.uniques')

          echo "views=$views" >> $GITHUB_OUTPUT
          echo "uniques=$uniques" >> $GITHUB_OUTPUT

      - name: Update JSON file
        run: |
          echo "{\"views\": ${{ steps.traffic.outputs.views }}, \"unique\": ${{ steps.traffic.outputs.uniques }}}" > stats/views.json

      - name: Update README
        run: |
          views=${{ steps.traffic.outputs.views }}
          uniques=${{ steps.traffic.outputs.uniques }}

          sed -i "s/Views:.*/Views: $views | Unique: $uniques/" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add stats/views.json README.md
          git commit -m "update views counter" || exit 0
          git push